version: '3.4'

services: 
    catalogdb: 
        container_name: catalogdb
        restart: always
        volumes: 
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
            #- ./data:/data/db
        ports:  
           - "27018:27017"

    catalog.api: 
        container_name: catalogapi
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - "CatalogDatabaseSettings_ConnectionString=mongodb://catalogdb:27018"   
        depends_on:  
            - catalogdb  
        volumes: 
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:  
            - "8000:80"